# Generated by Django 5.1.5 on 2025-03-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_remove_disease_symptoms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disease",
            name="description",
        ),
    ]
