# Generated by Django 5.1.5 on 2025-03-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_rename_gradcam_path_analysis_gradcam_pat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysis",
            old_name="gradcam_pat",
            new_name="gradcam_path",
        ),
    ]
